"""Initial migration

Revision ID: f710b738165c
Revises: 
Create Date: 2022-07-22 19:49:30.236226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f710b738165c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_user', sa.String(), nullable=False),
    sa.Column('email_user', sa.String(), nullable=False),
    sa.Column('desc_task', sa.Text(), nullable=False),
    sa.Column('is_edit_admin', sa.Boolean(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
